CREATE TABLE `trade_main` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sid` bigint unsigned DEFAULT 0,
  `tid` varchar(256) DEFAULT '',
  `company_id` bigint unsigned DEFAULT 0,
  `warehouse_id` bigint unsigned DEFAULT 0,
  `waybill_number` varchar(256) DEFAULT '',
  `template_id` bigint unsigned DEFAULT 0,
  `sys_status` varchar(256) DEFAULT '',
  `create_method` varchar(256) DEFAULT '',
  `platform_code` varchar(256) DEFAULT '',
  `platform_name` varchar(256) DEFAULT '',
  `remark` varchar(512) DEFAULT '',
  `send_province` varchar(256) DEFAULT '',
  `send_city` varchar(256) DEFAULT '',
  `send_distinct` varchar(256) DEFAULT '',
  `send_town` varchar(256) DEFAULT '',
  `send_detail` varchar(256) DEFAULT '',
  `send_code` varchar(256) DEFAULT '',
  `receiver_name` varchar(256) DEFAULT '',
  `receiver_province` varchar(256) DEFAULT '',
  `receiver_city` varchar(256) DEFAULT '',
  `receiver_distinct` varchar(256) DEFAULT '',
  `receiver_town` varchar(256) DEFAULT '',
  `receiver_detail` varchar(256) DEFAULT '',
  `receiver_code` varchar(256) DEFAULT '',
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `deleted_at` (`deleted_at`),
  index `idx_sid` (`sid`),
  index `idx_tid` (`company_id`, `tid`),
  index `idx_company_id_updated_at` (`company_id`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `trade_has_many` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `sid` bigint unsigned DEFAULT '0',
  `order_id` bigint unsigned DEFAULT '0',
  `company_id` bigint unsigned DEFAULT '0',
  `type` bigint unsigned DEFAULT '0',
  `type_name` varchar(256) DEFAULT '',
  `unit_id` bigint unsigned DEFAULT '0',
  `unit_name` varchar(256) DEFAULT '',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_sid` (`sid`),
  KEY `idx_oid` (`order_id`),
  KEY `idx_company_id_type_unit_id` (`company_id`,`type`,`unit_id`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;